### ISSUE TITLE
UI for milestone payout requests

### ISSUE THREAD

**Issue by delightfulabyss** [0xPrimordia/impact-stream-app#189]
- User instigates a safe transaction comprised of transferring milestone amount from safe to Impact Stream address
- Will need some sort of fiat to crypto conversion on front-end
- We need to get the Impact Stream multisig address from Will
- [Impact Stream will need to provide additional signatures on the Safe transactions and execute them either from the Safe UI or via the sdk](https://docs.safe.global/safe-core-aa-sdk/protocol-kit#confirm-the-transaction-second-confirmation)
- [Safe Architecture](https://docs.safe.global/safe-core-api/service-architecture)
- [Safe Protocol Kit Docs](https://docs.safe.global/safe-core-aa-sdk/protocol-kit)

### Steps to create and propose Safe transaction:
1. [Get Ethers provider and signer from Privy 
](https://docs.privy.io/guide/frontend/embedded/usage/3p-libraries) 
3. [Instantiate an Eth Adapter with the signer from Privy](https://github.com/safe-global/safe-core-sdk/tree/main/packages/protocol-kit/src/adapters/ethers)
4. [Instantiate an SDK instance with the EthAdapter and the user's associated Safe address from Supabase](https://github.com/safe-global/safe-core-sdk/tree/main/packages/protocol-kit#create-1)
5. [Create a transaction with the amount of the milestone payout (converted from CFA amount) and the IS multisig as the 'to' address](https://docs.safe.global/safe-core-aa-sdk/protocol-kit#create-a-transaction)
6. [Propose the transaction to the Safe Transaction Service](https://docs.safe.global/safe-core-aa-sdk/protocol-kit#propose-the-transaction)

**Comment by kevincompton** [comment]
![Image](https://github.com/0xPrimordia/impact-stream-app/assets/3978237/ca02490c-4a47-4846-b0de-8ec4eb02791e)

**Comment by kevincompton** [comment]
@delightfulabyss I need details for this one asap

**Comment by delightfulabyss** [comment]
> @delightfulabyss I need details for this one asap

Added instructions!
