### ISSUE TITLE
Update calls to voting with non-hard coded values

### ISSUE THREAD

**Issue by 0xZakk** [0xPrimordia/impact-stream-app#234]
Values were hard-coded in for demonstration purposes. Recipient Id will need to be sourced from Supabase.

Call to vote  is `allocate(uint poolId, bytes data)` on Allo contract and data to provide is `abi.encode(address recipientId, uint voiceCreditsToAllocate)`

**Comment by 0xZakk** [comment]
@delightfulabyss

**Comment by kevincompton** [comment]
This info Matt said was based on the update from your team, I recommend whoever left off with voting take this issue.
