### ISSUE TITLE
Figure Out Saving and Reading from IPFS

### ISSUE THREAD

**Issue by delightfulabyss** [0xPrimordia/impact-stream-app#236]
We cannot use the Web3.storage sdk to create file objects in memory programmatically using data from Supabase  (avoids having to upload actual files) because the file system API only exists in the browser and not in nodeJS.

We will need to go back to the original plan of uploading metadata JSON files to IPFS beforehand prior to calling the scripts. 

We need to:
1. Determine what information we are uploading to be associated with Allo profiles
2. Determine where we are saving and reading the resulting urls from (CSV import, database call, etc)

Potential solutions:
- Create and upload the files ourselves and save the URLs to be read by admin scripts
- Have the admin scripts read the files and perform the uploads
- Upload data via file system API using the front-end at some point in the user flow

**Comment by 0xZakk** [comment]
Metadata: JSON object with ID in Supabase (and nothing else)

**Comment by delightfulabyss** [comment]
^Decision was to upload this retroactively for current users and via the onboarding flow for new users
