### ISSUE TITLE
Bug: Fix overlapping button and toast

### ISSUE THREAD

**Issue by 0xZakk** [0xPrimordia/impact-stream-app#237]
On some phone dimensions the toast message and Create Proposal button overlap

![Image](https://github.com/0xPrimordia/impact-stream-app/assets/4991553/8c33e7e1-4bd7-46f6-bbd0-821a65611a0b)

**Comment by kevincompton** [comment]
@0xZakk Unable to replicate this with any of the preset mobile sizes in Brave and I don't see the issue with the responsive setting unless I go all the way down to 280px wide, but it still looks different that this screen. Can you check what sizes you see this on and let me know?
