### ISSUE TITLE
Bug: Flash of being logged out

### ISSUE THREAD

**Issue by 0xZakk** [0xPrimordia/impact-stream-app#241]
When I click on the logo to go back to the homepage, the screen flashes as if I'm logged out even though I'm not. 

![Image](https://github.com/0xPrimordia/impact-stream-app/assets/4991553/7e043793-aa95-4382-866b-4885fe9fa9f1)

**Comment by kevincompton** [comment]
This happens often and has somethig to do with the privy session, @delightfulabyss ca you have a look at this one?
