### ISSUE TITLE
QOL: Decide between 'Grant' or 'Proposal'

### ISSUE THREAD

**Issue by kevincompton** [0xPrimordia/impact-stream-app#253]
I think this term should be consistent for the UX as well as our code base, currently we are using both terms with a fairly loose distinction. Practically it is one thing that moves along in stages and we only have one model in the database, "Proposal".

Action items:
1. Merge Grant logic into the proposal folder and change all code and file names to reference proposal instead of grant so that it's consistent with our database structure.
2. For the UX get clarity on it's use from the Impact Stream core team, recommend we simplify to one.

**Comment by 0xZakk** [comment]
Let's go with "Proposal"

What's the LOE for item 1?

**Comment by kevincompton** [comment]
It should take about an hour but I'd rather that whoever created the Grant folder handle this issue that so I don't miss any pieces.
