### ISSUE TITLE
Cart Icon not showing right number

### ISSUE THREAD

**Issue by codenamejason** [0xPrimordia/impact-stream-app#265]

**Comment by codenamejason** [comment]
![Image](https://github.com/0xPrimordia/impact-stream-app/assets/9419140/9ae10fd5-9bdb-4ea7-bde9-e5d2ff0e78ad)

Should show a `2` not a `3`

**Comment by thelostone-mc** [comment]
Clear local storage and try again and it should work

**Comment by thelostone-mc** [comment]
Fixed via f622b2e
